### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by frischnetz** [Rillke/fritzXML2vcard#139]
Hi!

I got the same error on the web version and the Node.js-Version with a file exported from fritzbox. The file looks fine (at first glance), it closes with ```</phonebooks>``` and has about 500 lines.

The JS version's error message reads:
``` [lippmann@norman Downloads]$ fritz-xml-2vcard FRITZ.Box_Telefonbuch_29.05.22_1740.xml .
/home/lippmann/.nvm/versions/node/v10.23.0/lib/node_modules/fritz-xml-2vcard/src/lib-convert.js:66
						var phoneNumber = [number._Data.trim()],
						                                ^

TypeError: Cannot read property 'trim' of undefined
    at run (/home/lippmann/.nvm/versions/node/v10.23.0/lib/node_modules/fritz-xml-2vcard/src/lib-convert.js:66:39)
    at Object.module.exports.fritzXML2vcard (/home/lippmann/.nvm/versions/node/v10.23.0/lib/node_modules/fritz-xml-2vcard/src/lib-convert.js:110:10)
    at /home/lippmann/.nvm/versions/node/v10.23.0/lib/node_modules/fritz-xml-2vcard/convert.js:74:23
    at Object.<anonymous> (/home/lippmann/.nvm/versions/node/v10.23.0/lib/node_modules/fritz-xml-2vcard/convert.js:81:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

**Comment by Rillke** [comment]
Thanks for reporting. It seems you have something like this in your phonebook (number without a number):

```xml
			<telephony nid="1">
				<number type="work" prio="1" id="0"></number>
			</telephony>
```

OR

```xml
			<telephony nid="1">
				<number type="work" prio="1" id="0" />
			</telephony>
```

fx2vc should not throw an error while parsing that. Going to fix this.

**Comment by Rillke** [comment]
Hi @frischnetz, can you please retry Version: 6882e5c / v3.0.4 ? If your browser has cached the website, please hold Shift, then press reload, in order to bypass your browser's cache. Thanks!

**Comment by frischnetz** [comment]
Hi @Rillke ,

I tried the latest version on the website with the same file that threw the error before and now it worked flawlessly! Thanks for the quick fix! Also from my father who I was trying to move his addresses.
